### PR TITLE
Initial pass at Blockchain Guild purpose

### PR DESCRIPTION
**Pull request by ChristopherA**
An initial pass for the next of the Blockchain Guild purpose. 

I'd like to get an ACK from all involved as this should be a community decision: 

@brunocvcunha
@snomofomo
@kallewoof
@hierophantos
@jimmysong

### CODE REVIEW

**Comment by ChristopherA** [comment]
Also would like ACK from @TuurDemeester, a patron.

**Comment by kallewoof** [comment]
ACK from me

**Comment by brunocvcunha** [comment]
Looks good to me! Thanks

**Comment by snomofomo** [comment]
ACK

**Comment by TuurDemeester** [comment]
Done

On Dec 26, 2017 12:03 PM, "Christopher Allen" <notifications@github.com>
wrote:

Also would like ACK from @TuurDemeester <https://github.com/tuurdemeester>,
a patron.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BlockchainGuild/BlockchainGuildCommunity/pull/10#issuecomment-353995839>,
or mute the thread

**Comment by ChristopherA** [comment]
5 ACKs, no NACKs. Approved. Still open to additional improvements and suggestions.

**Pull request merged**
